### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by sapegin** [hubgit/react-prosemirror#1]
Looks like the project is in active development but there’s no docs except the demo. Is it ready for production use? Would be nice to have a Readme with some instructions.

P. S. It’s awesome that you use Styleguidist for the docs ❤️

**Comment by sapegin** [comment]
Ha, it’s inside packages ;-) I’ll submit a PR with a basic main readme that will point to packages.

**Comment by hubgit** [comment]
Thanks, I'd been meaning to do that! 😃

**Comment by hubgit** [comment]
> Is it ready for production use?

I'd say expect breaking changes for a little while, there are still some things I haven't completely figured out how best to implement.
