### ISSUE TITLE
Changing placeholder and styling elements

### ISSUE THREAD

**Issue by yusufola** [hubgit/react-prosemirror#11]
I'm finding it difficult to change the placeholder of the HtmlEditor and also add style. Documentation on this will be highly appreciated

**Comment by hubgit** [comment]
The content and style of the placeholder are currently set in [`placeholder.css`](https://github.com/hubgit/react-prosemirror/blob/master/prosemirror-placeholder/style/placeholder.css), although there's [an open issue](https://github.com/hubgit/react-prosemirror/issues/3) for allowing the content to be passed in as an attribute.
