### ISSUE TITLE
render on update for redux state

### ISSUE THREAD

**Issue by fliropp** [hubgit/react-prosemirror#12]
Somehow value inside the htmlEditor tag does to reflect updated Redux state although it re-renders on  new state? I might be a little tired here, but I just can' seam to get the new state to display in the editor window

**Comment by hubgit** [comment]
This is probably because the Editor component doesn't yet have a `componentWillReceiveProps` method - it simply takes an initial value.

**Comment by t3db0t** [comment]
Hey, one year later—what is the status of this? I'm using Prosemirror in a react-redux project and I'm currently trying to wrap my head around it all X-)

**Comment by hubgit** [comment]
If you're interested in trying v2, you could add a component inside `EditorProvider` that uses `const view = useEditorView()` to get the editor view and call `view.updateState(state)` with the new state when needed.
