### ISSUE TITLE
[Question] Consider configurable debounce time?

### ISSUE THREAD

**Issue by OwenMelbz** [hubgit/react-prosemirror#20]
Hi,

We were wondering if you would consider allowing the debounce time to be configurable?

We've a situations where users are clicking save buttons before the debounce has triggered an onChange which is causing users to lose data :(

Thanks!

**Comment by hubgit** [comment]
How about (optionally) passing the ProseMirror doc straight through to the `onChange` handler whenever it changes, so your application can keep track of changes that still need to be saved and can serialize the doc to HTML whenever is most appropriate?

**Comment by OwenMelbz** [comment]
@hubgit Hi,

Sorry would you be able to provide a super basic example of what exactly you mean please?

Thanks

**Comment by hubgit** [comment]
Actually I just noticed that only `HtmlEditor` uses the debounce, so maybe if you used `Editor` directly and called `parse` and `serialize` in your code that would solve the problem?

**Comment by hubgit** [comment]
If you're interested in trying v2, the new `ChangeHandler` component can be configured using the `debounce` parameter.

Alternatively, you could add a component that only serialises the editor state when a button is pressed.
