### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by mattcopas** [hubgit/react-prosemirror#8]
Hi,

I'd like to try using your lib using Typescript, but there's no type declaration file (index.d.ts), or a corresponding @types library on NPM. 

Do you have any plan/would you add type declarations?

Cheers

**Comment by charlex** [comment]
This seems like it may be difficult to accomplish, because it would be asking the maintainer of the @types package or the maintainer of this project to keep up with how the prose mirror API changes, right?

**Comment by strogonoff** [comment]
(FWIW it’s possible to provide typings using a .d.ts file inside the project itself.)

I’ll try to add some dummy opt-out declarations inside my current project to silence TS, but definitely hoping both this and the config-default packages are typed properly at some point by a knowledgeable person. I’ll be sure to create a PR when my typing skills are at suitable level, but I’m far from there yet.

**Comment by charlex** [comment]
@strogonoff I'd love to see TypeScript definitions for this project personally. Do keep us posted if you make any progress, please!

**Comment by hubgit** [comment]
I have a plan to rewrite the whole project in TypeScript, if I can find time.

**Comment by hubgit** [comment]
I've started writing v2 in TypeScript - it's a different approach that will hopefully prove to be more extensible.

https://github.com/hubgit/react-prosemirror/tree/v2

**Comment by hubgit** [comment]
v2 is now released, rewritten in TypeScript.

The way the React components work is a bit different, but you should be able to use the same schema, plugins, etc.
